"""
Report Generator — produces a styled HTML summary report
Simulates RPA output report generation (like Word/PDF reports from AA bots)
"""

import pandas as pd
from datetime import datetime


def generate_html_report(df: pd.DataFrame) -> str:
    """Generate a styled HTML report from processing results."""
    total = len(df)
    processed = len(df[df["status"] == "processed"])
    flagged = len(df[df["status"] == "flagged_for_review"])
    avg_conf = df["confidence"].mean()
    cat_counts = df.groupby("category")["query_id"].count().to_dict()
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    cat_rows = "".join(
        f"<tr><td>{cat}</td><td>{count}</td><td>{count/total:.0%}</td></tr>"
        for cat, count in cat_counts.items()
    )

    query_rows = "".join(
        f"""<tr>
            <td>{row.query_id}</td>
            <td>{row.customer_name}</td>
            <td>{row.query_text[:60]}...</td>
            <td><span class="badge {'badge-success' if row.category == 'general_enquiry' else 'badge-primary'}">{row.category}</span></td>
            <td>{row.confidence:.0%}</td>
            <td><span class="badge {'badge-success' if row.status == 'processed' else 'badge-warning'}">{row.status}</span></td>
        </tr>"""
        for row in df.itertuples()
    )

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Query Processing Report</title>
<style>
  body {{ font-family: Arial, sans-serif; margin: 40px; color: #333; }}
  h1 {{ color: #1F4E79; border-bottom: 3px solid #2E75B6; padding-bottom: 10px; }}
  h2 {{ color: #2E75B6; margin-top: 30px; }}
  .metrics {{ display: flex; gap: 20px; margin: 20px 0; }}
  .metric {{ background: #EEF4FB; border-left: 4px solid #2E75B6; padding: 15px 20px; border-radius: 4px; min-width: 120px; }}
  .metric-value {{ font-size: 28px; font-weight: bold; color: #1F4E79; }}
  .metric-label {{ font-size: 13px; color: #666; margin-top: 4px; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 15px; font-size: 13px; }}
  th {{ background: #1F4E79; color: white; padding: 10px; text-align: left; }}
  td {{ padding: 9px 10px; border-bottom: 1px solid #ddd; }}
  tr:hover {{ background: #f5f9ff; }}
  .badge {{ padding: 3px 8px; border-radius: 12px; font-size: 11px; font-weight: bold; }}
  .badge-success {{ background: #d4edda; color: #155724; }}
  .badge-primary {{ background: #cce5ff; color: #004085; }}
  .badge-warning {{ background: #fff3cd; color: #856404; }}
  .footer {{ margin-top: 40px; font-size: 12px; color: #999; border-top: 1px solid #eee; padding-top: 10px; }}
</style>
</head>
<body>
<h1>🤖 Customer Query Processing Report</h1>
<p>Generated: {generated_at} | Pipeline: RPA + AI Hybrid (HuggingFace NLP)</p>

<h2>Summary Metrics</h2>
<div class="metrics">
  <div class="metric"><div class="metric-value">{total}</div><div class="metric-label">Total Queries</div></div>
  <div class="metric"><div class="metric-value">{processed}</div><div class="metric-label">Auto-Processed</div></div>
  <div class="metric"><div class="metric-value">{flagged}</div><div class="metric-label">Flagged for Review</div></div>
  <div class="metric"><div class="metric-value">{avg_conf:.0%}</div><div class="metric-label">Avg Confidence</div></div>
  <div class="metric"><div class="metric-value">{processed/total:.0%}</div><div class="metric-label">Automation Rate</div></div>
</div>

<h2>Classification Breakdown</h2>
<table>
  <tr><th>Category</th><th>Count</th><th>% of Total</th></tr>
  {cat_rows}
</table>

<h2>Detailed Results</h2>
<table>
  <tr><th>Query ID</th><th>Customer</th><th>Query</th><th>Category</th><th>Confidence</th><th>Status</th></tr>
  {query_rows}
</table>

<div class="footer">
  Generated by RPA + AI Hybrid Automation Pipeline | Author: Sushma Nadkarni
</div>
</body>
</html>"""
